# yaml-language-server: $schema=https://taskfile.dev/schema.json

version: '3'

vars:
  GREETING: Hello, world!

tasks:
  run:
    desc: Run the project
    cmds:
      - streamlit run main.py
    # silent: true
